---
# tasks file for roles/docker

- name: "DOCKER | install docker"
  ansible.builtin.import_tasks: section0.yml
  become: true
  tags:
    - docker
    - section0

- name: "DOCKER | section1"
  ansible.builtin.import_tasks: section1.yml
  become: true
  when: docker_cis_section1 | bool
  tags:
    - docker
    - section1

- name: "DOCKER | section2"
  ansible.builtin.import_tasks: section2.yml
  become: true
  when: docker_cis_section2 | bool
  tags:
    - docker
    - section2

- name: "DOCKER | section3"
  ansible.builtin.import_tasks: section3.yml
  become: true
  when: docker_cis_section3 | bool
  tags:
    - docker
    - section3
