---
# tasks file for ansible-docker

# ------------------------------------------------------------------------------

- name: "IMPORT TASK | pre"
  ansible.builtin.import_tasks: pre.yml
  become: true
  tags:
    - pre
    - docker

# ------------------------------------------------------------------------------

- name: "IMPORT TASK | install"
  ansible.builtin.import_tasks: install.yml
  become: true
  when: cis_docker_section_install
  tags:
    - install
    - docker

# ------------------------------------------------------------------------------

- name: "IMPORT TASK | section1"
  ansible.builtin.import_tasks: section1.yml
  become: true
  when: cis_docker_section1
  tags:
    - section1
    - docker

- name: "IMPORT TASK | section2"
  ansible.builtin.import_tasks: section2.yml
  become: true
  when: cis_docker_section2
  tags:
    - section2
    - docker

- name: "IMPORT TASK | section3"
  ansible.builtin.import_tasks: section3.yml
  become: true
  when: cis_docker_section3
  tags:
    - section3
    - docker

- name: "IMPORT TASK | section4"
  ansible.builtin.import_tasks: section4.yml
  become: true
  when: cis_docker_section4
  tags:
    - section4
    - docker

- name: "IMPORT TASK | section5"
  ansible.builtin.import_tasks: section5.yml
  become: true
  when: cis_docker_section5
  tags:
    - section5
    - docker

- name: "IMPORT TASK | section6"
  ansible.builtin.import_tasks: section6.yml
  become: true
  when: cis_docker_section6
  tags:
    - section6
    - docker

- name: "IMPORT TASK | section7"
  ansible.builtin.import_tasks: section7.yml
  become: true
  when: cis_docker_section7
  tags:
    - section7
    - docker
