---
# tasks file for ansible-docker

# ------------------------------------------------------------------------------

- name: "PRE | 1.1.3 - 1.1.18 | check if 'auditd' package is installed"
  ansible.builtin.command: dpkg -V auditd
  register: cis_docker_package_installed_auditd
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - docker
    - pre
