---
# tasks file for ansible-docker

# ------------------------------------------------------------------------------

# - name: "SECTION1 | 1.1.1 | Ensure a separate partition for containers has been created"
#   # TODO: need rule
#   when:
#     - cis_docker_rule_1_1_1
#   tags:
#     - rule_1.1.1

# ------------------------------------------------------------------------------

- name: "SECTION1 | 1.1.2 | Ensure only trusted users are allowed to control Docker daemon"
  when:
    - cis_docker_rule_1_1_2
    - cis_docker_users_to_add_group is defined
  tags:
    - rule_1_1_2
  block:
    - name: "SECTION1 | 1.1.2 | Ensure only trusted users are allowed to control Docker daemon | create docker group"
      ansible.builtin.group:
        name: "{{ cis_docker_group_default }}"
        state: present
        system: true
    - name: "SECTION1 | 1.1.2 | Ensure only trusted users are allowed to control Docker daemon | create docker user"
      ansible.builtin.user:
        name: "{{ cis_docker_user_default }}"
        group: "{{ cis_docker_group_default }}"
        groups: "{{ cis_docker_group_default }}"
        comment: "manage docker access"
        system: true
        shell: "{{ cis_docker_user_shell }}"
    - name: "SECTION1 | 1.1.2 | Ensure only trusted users are allowed to control Docker daemon | adding users to group {{ cis_docker_group_default }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ cis_docker_group_default }}"
        append: true
      loop: "{{ cis_docker_users_to_add_group | flatten(levels=1) }}"

# ------------------------------------------------------------------------------

- name: "SECTION1 | 1.1.3 | Ensure auditing is configured for the Docker daemon"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/dockerd{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/dockerd -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_3
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_3

- name: "SECTION1 | 1.1.4 | Ensure auditing is configured for Docker files and directories - /run/containerd"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-a exit,always -F path=/run/containerd{{ cis_docker_regex_base_search_end }}"
    line: "-a exit,always -F path=/run/containerd -F perm=war -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_4
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_4

- name: "SECTION1 | 1.1.5 | Ensure auditing is configured for Docker files and directories - /var/lib/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-a exit,always -F path=/var/lib/docker{{ cis_docker_regex_base_search_end }}"
    line: "-a exit,always -F path=/var/lib/docker -F perm=war -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_5
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_5

- name: "SECTION1 | 1.1.6 | Ensure auditing is configured for Docker files and directories - /etc/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /etc/docker{{ cis_docker_regex_base_search_end }}"
    line: "-w /etc/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_6
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_6

- name: "SECTION1 | 1.1.7 | Ensure auditing is configured for Docker files and directories - docker.service"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/lib/systemd/system/docker.service{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_7
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_7

- name: "SECTION1 | 1.1.8 | Ensure auditing is configured for Docker files and directories - containerd.sock"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /run/containerd/containerd.sock{{ cis_docker_regex_base_search_end }}"
    line: "-w /run/containerd/containerd.sock -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_8
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_8

- name: "SECTION1 | 1.1.9 | Ensure auditing is configured for Docker files and directories - docker.socket"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /var/run/docker.sock{{ cis_docker_regex_base_search_end }}"
    line: "-w /var/run/docker.sock -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_9
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_9

- name: "SECTION1 | 1.1.10 | Ensure auditing is configured for Docker files and directories - /etc/default/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /etc/default/docker{{ cis_docker_regex_base_search_end }}"
    line: "-w /etc/default/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_10
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_10

- name: "SECTION1 | 1.1.11 | Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /etc/docker/daemon.json{{ cis_docker_regex_base_search_end }}"
    line: "-w /etc/docker/daemon.json -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_11
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_11

- name: "SECTION1 | 1.1.12 | Ensure auditing is configured for Docker files and directories - /etc/containerd/config.toml"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /etc/containerd/config.toml{{ cis_docker_regex_base_search_end }}"
    line: "-w /etc/containerd/config.toml -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_12
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_12

- name: "SECTION1 | 1.1.13 | Ensure auditing is configured for Docker files and directories - /etc/sysconfig/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /etc/sysconfig/docker{{ cis_docker_regex_base_search_end }}"
    line: "-w /etc/sysconfig/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_13
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_13

- name: "SECTION1 | 1.1.14 | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/containerd{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/containerd -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_14
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_14

- name: "SECTION1 | 1.1.15 | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/containerd-shim{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/containerd-shim -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_15
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_15

- name: "SECTION1 | 1.1.16 | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v1"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/containerd-shim-runc-v1{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/containerd-shim-runc-v1 -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_16
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_16

- name: "SECTION1 | 1.1.17 | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v2"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/containerd-shim-runc-v2{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/containerd-shim-runc-v2 -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_17
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_17

- name: "SECTION1 | 1.1.18 | Ensure auditing is configured for Docker files and directories - /usr/bin/runc"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/cis_docker_rule_1_1_3-18.rules
    regexp: "{{ cis_docker_regex_base_search }}-w /usr/bin/runc{{ cis_docker_regex_base_search_end }}"
    line: "-w /usr/bin/runc -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - cis_docker_rule_1_1_18
    - cis_docker_package_installed_auditd.rc == 0
  notify:
    - Restart auditd-service
  tags:
    - rule_1_1_18

# ------------------------------------------------------------------------------

- name: "SECTION1 | 1.2.1 | Ensure the container host has been Hardened"
  when:
    - cis_docker_rule_1_2_1
  tags:
    - rule_1_2_1
  block:
    - name: "SECTION1 | 1.2.1 | Ensure the container host has been Hardened | print info"
      ansible.builtin.debug:
        msg: |
          #############################################################################################
          Ensure the container host has been Hardened
          #############################################################################################

- name: "SECTION1 | 1.2.2 | Ensure that the version of Docker is up to date"
  when:
    - cis_docker_rule_1_2_2
  tags:
    - rule_1_2_2
  block:
    - name: "SECTION1 | 1.2.2 | Ensure that the version of Docker is up to date | get info"
      ansible.builtin.shell: docker version
      args:
        executable: "{{ cis_docker_user_shell }}"
      register: cis_docker_1_2_2_version
      changed_when: false
      failed_when: false
      check_mode: false
    - name: "SECTION1 | 1.2.2 | Ensure that the version of Docker is up to date | print info"
      ansible.builtin.debug:
        msg: |
          #############################################################################################
          Ensure that the version of Docker is up to date
          #############################################################################################
          {{ cis_docker_1_2_2_version.stdout_lines | join(cis_docker_print_info_join_by) }}
          #############################################################################################
