---
# tasks file for ansible-docker

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.1 | Ensure that the docker.service file ownership is set to docker user (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "~/.config/systemd/user/docker.service"
    owner: "{{ cis_docker_user_default }}"
    group: "{{ cis_docker_group_default }}"
    state: file
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_1
  tags:
    - rule_3_1

- name: "SECTION3 | 3.1 | Ensure that the docker.service file ownership is set to root:root"
  ansible.builtin.file:
    path: "/usr/lib/systemd/system/docker.service"
    owner: "root"
    group: "root"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_1
  tags:
    - rule_3_1

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.2 | Ensure that docker.service file permissions are appropriately set (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "~/.config/systemd/user/docker.service"
    mode: "0640"
    state: file
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_2
  tags:
    - rule_3_2

- name: "SECTION3 | 3.2 | Ensure that docker.service file permissions are appropriately set"
  ansible.builtin.file:
    path: "/usr/lib/systemd/system/docker.service"
    mode: "0644"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_2
  tags:
    - rule_3_2

# ------------------------------------------------------------------------------

# - name: "SECTION3 | 3.3 | Ensure that docker.socket file ownership is set docker user (ROOTLESS)"
#   become: true
#   become_user: "{{ cis_docker_user_default }}"
#   ansible.builtin.file:
#     path: "~/.config/systemd/user/docker.socket"
#     owner: "{{ cis_docker_user_default }}"
#     group: "{{ cis_docker_group_default }}"
#     state: file
#   when:
#     - cis_docker_rule_2_1
#     - cis_docker_rule_3_3
#   tags:
#     - rule_3_3

- name: "SECTION3 | 3.3 | Ensure that docker.socket file ownership is set to root:root"
  ansible.builtin.file:
    path: "/usr/lib/systemd/system/docker.socket"
    owner: "root"
    group: "root"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_3
  tags:
    - rule_3_3

# ------------------------------------------------------------------------------

# - name: "SECTION3 | 3.4 | Ensure that docker.socket file permissions are set to 644 or more restrictive (ROOTLESS)"
#   become: true
#   become_user: "{{ cis_docker_user_default }}"
#   ansible.builtin.file:
#     path: "~/.config/systemd/user/docker.socket"
#     mode: "0640"
#     state: file
#   when:
#     - cis_docker_rule_2_1
#     - cis_docker_rule_3_4
#   tags:
#     - rule_3_4

- name: "SECTION3 | 3.4 | Ensure that docker.socket file permissions are set to 644 or more restrictive"
  ansible.builtin.file:
    path: "/usr/lib/systemd/system/docker.socket"
    mode: "0644"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_4
  tags:
    - rule_3_4

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.5 | Ensure that the nonroot docker directory ownership is set to docker user (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_rootless }}"
    owner: "{{ cis_docker_user_default }}"
    group: "{{ cis_docker_group_default }}"
    mode: "0750"
    state: directory
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_5
  tags:
    - rule_3_5

- name: "SECTION3 | 3.5 | Ensure that the /etc/docker directory ownership is set to root:root"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_root }}"
    owner: "root"
    group: "root"
    mode: "0750"
    state: directory
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_5
  tags:
    - rule_3_5

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.6 | Ensure that nonroot docker directory permissions are set to 755 or more restrictively"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_rootless }}"
    mode: "0750"
    state: directory
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_6
  tags:
    - rule_3_6

- name: "SECTION3 | 3.6 | Ensure that /etc/docker directory permissions are set to 755 or more restrictively"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_root }}"
    mode: "0750"
    state: directory
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_6
  tags:
    - rule_3_6

# ------------------------------------------------------------------------------

# - name: "SECTION3 | 3.7 | Ensure that registry certificate file ownership is set to root:root"
# - name: "SECTION3 | 3.8 | Ensure that registry certificate file permissions are set to 444 or more restrictively"
# - name: "SECTION3 | 3.9 | Ensure that TLS CA certificate file ownership is set to root:root"
# - name: "SECTION3 | 3.10 | Ensure that TLS CA certificate file permissions are set to 444 or more restrictively"
# - name: "SECTION3 | 3.11 | Ensure that Docker server certificate file ownership is set to root:root"
# - name: "SECTION3 | 3.12 | Ensure that the Docker server certificate file permissions are set to 444 or more restrictively"
# - name: "SECTION3 | 3.13 | Ensure that the Docker server certificate key file ownership is set to root:root"
# - name: "SECTION3 | 3.14 | Ensure that the Docker server certificate key file permissions are set to 400"

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.15 | Ensure that the Docker socket file ownership is set to docker user (ROOTLESS)"
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_15
  tags:
    - rule_3_15
  block:
    - name: "SECTION3 | 3.15 | Ensure that the Docker socket file ownership is set to docker user"
      ansible.builtin.file:
        path: "/var/run/user/{{ getent_passwd[cis_docker_user_default][1] }}/docker.sock"
        owner: "{{ cis_docker_user_default }}"
        group: "{{ cis_docker_group_default }}"
        state: file
    - name: "SECTION3 | 3.15 | Ensure that the Docker socket directory ownership is set to docker user"
      ansible.builtin.file:
        path: "/var/run/user/{{ getent_passwd[cis_docker_user_default][1] }}"
        owner: "{{ cis_docker_user_default }}"
        group: "{{ cis_docker_group_default }}"
        mode: "0770"
        state: directory

- name: "SECTION3 | 3.15 | Ensure that the Docker socket file ownership is set to root:docker"
  ansible.builtin.file:
    path: "/var/run/docker.sock"
    owner: "root"
    group: "{{ cis_docker_group_default }}"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_15
  tags:
    - rule_3_15

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.16 | Ensure that the Docker socket file permissions are set to 660 or more restrictively (ROOTLESS)"
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_16
  tags:
    - rule_3_16
  block:
    - name: "SECTION3 | 3.16 | Ensure that the Docker socket file permissions are set to 660 or more restrictively"
      ansible.builtin.file:
        path: "/var/run/user/{{ getent_passwd[cis_docker_user_default][1] }}/docker.sock"
        mode: "0660"
        state: file
    - name: "SECTION3 | 3.16 | Ensure that the Docker socket directory permissions are set to 770 or more restrictively"
      ansible.builtin.file:
        path: "/var/run/user/{{ getent_passwd[cis_docker_user_default][1] }}"
        mode: "0770"
        state: directory

- name: "SECTION3 | 3.16 | Ensure that the Docker socket file permissions are set to 660 or more restrictively"
  ansible.builtin.file:
    path: "/var/run/docker.sock"
    mode: "0660"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_16
  tags:
    - rule_3_16

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.17 | Ensure that the daemon.json file ownership is set (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_rootless }}/daemon.json"
    owner: "{{ cis_docker_user_default }}"
    group: "{{ cis_docker_group_default }}"
    state: file
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_17
  tags:
    - rule_3_17

- name: "SECTION3 | 3.17 | Ensure that the daemon.json file ownership is set to root:root"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_root }}/daemon.json"
    owner: "root"
    group: "root"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_17
  tags:
    - rule_3_17

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.18 | Ensure that daemon.json file permissions are set to 644 or more restrictive (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_rootless }}/daemon.json"
    mode: "0640"
    state: file
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_18
  tags:
    - rule_3_18

- name: "SECTION3 | 3.18 | Ensure that daemon.json file permissions are set to 644 or more restrictive"
  ansible.builtin.file:
    path: "{{ cis_docker_daemon_json_root }}/daemon.json"
    mode: "0640"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_18
  tags:
    - rule_3_18

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.19 | Ensure that the /etc/default/docker file ownership is set to docker user (ROOTLESS)"
  ansible.builtin.file:
    path: "/etc/default/docker"
    owner: "{{ cis_docker_user_default }}"
    group: "{{ cis_docker_group_default }}"
    state: file
  when:
    - cis_docker_rule_2_1
    - cis_docker_rule_3_19
  tags:
    - rule_3_19

- name: "SECTION3 | 3.19 | Ensure that the /etc/default/docker file ownership is set to root:root"
  ansible.builtin.file:
    path: "/etc/default/docker"
    owner: "root"
    group: "root"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_19
  tags:
    - rule_3_19

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.22 | Ensure that the /etc/default/docker file permissions are set to 644 or more restrictively"
  ansible.builtin.file:
    path: "/etc/default/docker"
    mode: "0640"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_22
  tags:
    - rule_3_22

# ------------------------------------------------------------------------------

# - name: "SECTION3 | 3.20 | Ensure that the /etc/sysconfig/docker file permissions are set to 644 or more restrictively"
# - name: "SECTION3 | 3.21 | Ensure that the /etc/sysconfig/docker file ownership is set to root:root"

# ------------------------------------------------------------------------------

- name: "SECTION3 | 3.23 | Ensure that the Containerd socket file ownership is set to root:root"
  ansible.builtin.file:
    path: "/run/containerd/containerd.sock"
    owner: "root"
    group: "root"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_23
  tags:
    - rule_3_23

- name: "SECTION3 | 3.24 | Ensure that the Containerd socket file permissions are set to 660 or more restrictively"
  ansible.builtin.file:
    path: "/run/containerd/containerd.sock"
    mode: "0660"
    state: file
  when:
    - not cis_docker_rule_2_1
    - cis_docker_rule_3_24
  tags:
    - rule_3_24
