---
# tasks file for roles/docker

# ------------------------------------------------------------------------------
- name: "DOCKER | 0.0.0 | INSTALL | check python version for arg '--break-system-packages'"
  ansible.builtin.set_fact:
    py_extra_args: "--break-system-packages"
  when:
    - docker_install_pip is defined
    - docker_install_pip is not none
    - docker_install_pip | length>0
    - ansible_facts['python_version'] >= "3.11"
  tags:
    - docker

# ------------------------------------------------------------------------------
- name: "DOCKER | 0.0.1 | INSTALL | install docker dependencies (apt)"
  ansible.builtin.apt:
    pkg: "{{ docker_package_dependencies }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  when:
    - docker_package_dependencies is defined
    - docker_package_dependencies is not none
    - docker_package_dependencies | length>0
  tags:
    - docker

- name: "DOCKER | 0.0.1 | INSTALL | install docker dependencies (pip)"
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "{{ py_extra_args | default('') }}"
  loop: "{{ docker_pip_dependencies | flatten(levels=1) }}"
  when:
    - docker_pip_dependencies is defined
    - docker_pip_dependencies is not none
    - docker_pip_dependencies | length>0
  tags:
    - docker

# ------------------------------------------------------------------------------
- name: "DOCKER | 0.0.2 | INSTALL | add docker apt signing key, will not download if present"
  ansible.builtin.apt_key:
    url: "{{ docker_install_gpg.url }}"
    keyring: "{{ docker_install_gpg.path }}/{{ docker_install_gpg.name }}"
    state: present
  tags:
    - docker

- name: "DOCKER | 0.0.2 | INSTALL | get OS architecture"
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: os_architecture
  tags:
    - docker

- name: "DOCKER | 0.0.2 | INSTALL | get OS distribution"
  ansible.builtin.set_fact:
    lsb_release: "{{ ansible_lsb.codename | lower }}"
  tags:
    - docker

- name: "DOCKER | 0.0.2 | INSTALL | check if Docker repository is available"
  ansible.builtin.uri:
    url: "https://download.docker.com/linux/ubuntu/dists/{{ lsb_release }}/{{ docker_install_version }}"
    return_content: true
  ignore_errors: true
  register: docker_repo_check
  tags:
    - docker

- name: "DOCKER | 0.0.2 | INSTALL | choose fallback Docker repository"
  ansible.builtin.set_fact:
    lsb_release: "{{ docker_install_release_fallback }}"
  when: |
    (docker_repo_check is defined and docker_repo_check.status is defined and docker_repo_check.status != 200)
    or
    (lsb_release is defined and docker_install_release_skip_lunar is defined and docker_install_release_skip_lunar is not none and lsb_release == docker_install_release_skip_lunar)
  tags:
    - docker

- name: >
    DOCKER | 0.0.2 | INSTALL |
    add docker repository into sources list as:
    deb [arch={{ os_architecture.stdout }} signed-by={{ docker_install_gpg.path }}/{{ docker_install_gpg.name }}]
    {{ docker_install_repo }} {{ lsb_release }} {{ docker_install_version }}
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ os_architecture.stdout }} signed-by={{ docker_install_gpg.path }}/{{ docker_install_gpg.name }}]
      {{ docker_install_repo }} {{ lsb_release }} {{ docker_install_version }}
    state: present
  tags:
    - docker

# ------------------------------------------------------------------------------
- name: "DOCKER | 0.0.3 | INSTALL | install docker packages (apt)"
  ansible.builtin.apt:
    pkg: "{{ docker_install_apt }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  when:
    - docker_install_apt is defined
    - docker_install_apt is not none
    - docker_install_apt | length>0
  tags:
    - docker

# ------------------------------------------------------------------------------
- name: "DOCKER | 0.0.4 | INSTALL | get list of outdated pip packages"
  ansible.builtin.shell: >
    set -o pipefail &&
    python3 -m pip list -o | cut -f1 -d" " | tr " " "\n" | awk "{if(NR>=3)print}" | cut -d" " -f1
  args:
    executable: /bin/bash
  register: pip_outdated
  changed_when: pip_outdated.rc in [1]
  failed_when: pip_outdated.rc not in [0, 1]
  when:
    - docker_install_pip is defined
    - docker_install_pip is not none
    - docker_install_pip | length>0
    - docker_install_pip_update | bool
  tags:
    - docker

- name: "DOCKER | 0.0.4 | INSTALL | update all installed pip packages"
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--upgrade {{ py_extra_args | default('') }}"
  with_items: "{{ pip_outdated.stdout_lines }}"
  when:
    - docker_install_pip is defined
    - docker_install_pip is not none
    - docker_install_pip | length>0
    - docker_install_pip_update | bool
    - pip_outdated is defined
    - pip_outdated.stdout_lines is defined
  tags:
    - docker

- name: "DOCKER | 0.0.5 | INSTALL | install docker packages (pip)"
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "{{ py_extra_args | default('') }}"
  loop: "{{ docker_install_pip | flatten(levels=1) }}"
  when:
    - docker_install_pip is defined
    - docker_install_pip is not none
    - docker_install_pip | length>0
  tags:
    - docker
