---
# tasks file for ansible-docker

# ------------------------------------------------------------------------------

- name: "SECTION4 | 4.1 | Ensure that a user for the container has been created"
  when:
    - cis_docker_rule_4_1
  tags:
    - rule_4_1
  block:
    - name: "SECTION4 | 4.1 | Ensure that a user for the container has been created | get info"
      ansible.builtin.shell: >
        set -o pipefail && docker ps --quiet |
        xargs --max-args=1 -I{} docker exec {} cat /proc/1/status | grep '^Uid:' | awk '{print $3}'
      args:
        executable: "{{ cis_docker_user_shell }}"
      register: cis_docker_debug_4_user_container
      changed_when: false
      failed_when: false
      check_mode: false
    - name: "SECTION4 | 4.1 | Ensure that a user for the container has been created | print info"
      ansible.builtin.debug:
        msg: |
          #############################################################################################
          This should return the effective UID for each container and where it returns 0,
          it indicates that the container process is running as root.
          #############################################################################################
          {{ cis_docker_debug_4_user_container.stdout_lines | join(cis_docker_print_info_join_by) }}
          #############################################################################################

- name: "SECTION4 | 4.2 | Ensure that containers use only trusted base images"
  when:
    - cis_docker_rule_4_2
  tags:
    - rule_4_2
  block:
    - name: "SECTION4 | 4.2 | Ensure that containers use only trusted base images | get info"
      ansible.builtin.shell: docker images
      args:
        executable: "{{ cis_docker_user_shell }}"
      register: cis_docker_debug_4_trusted_base_images
      changed_when: false
      failed_when: false
      check_mode: false
    - name: "SECTION4 | 4.2 | Ensure that containers use only trusted base images | print info"
      ansible.builtin.debug:
        msg: |
          #############################################################################################
          This command lists all the container images that are currently available for use on the Docker host.
          You should then review the origin of each image and review its contents in line with your organization's security policy.
          #############################################################################################
          {{ cis_docker_debug_4_trusted_base_images.stdout_lines | join(cis_docker_print_info_join_by) }}
          #############################################################################################

# - name: "SECTION4 | 4.3 | Ensure that unnecessary packages are not installed in the container"
# - name: "SECTION4 | 4.4 | Ensure images are scanned and rebuilt to include security patches"
# - name: "SECTION4 | 4.5 | Ensure Content trust for Docker is Enabled"
# - name: "SECTION4 | 4.6 | Ensure that HEALTHCHECK instructions have been added to container images"
# - name: "SECTION4 | 4.7 | Ensure update instructions are not used alone in Dockerfiles"
# - name: "SECTION4 | 4.8 | Ensure setuid and setgid permissions are removed"
# - name: "SECTION4 | 4.9 | Ensure that COPY is used instead of ADD in Dockerfiles"
# - name: "SECTION4 | 4.10 | Ensure secrets are not stored in Dockerfiles"
# - name: "SECTION4 | 4.11 | Ensure only verified packages are installed"
# - name: "SECTION4 | 4.12 | Ensure all signed artifacts are validated"
