---
# tasks file for roles/docker

# ------------------------------------------------------------------------------
# - name: "AUTOMATED | 1.1.1 | PATCH | Ensure a separate partition for containers has been created"
#   # TODO: need rule
#   when:
#     - docker_cis_rule_1_1_1 | bool
#   tags:
#     - docker
#     - rule_1.1.1

# ------------------------------------------------------------------------------
- name: "AUTOMATED | 1.1.2 | PATCH | Ensure only trusted users are allowed to control Docker daemon | create docker group"
  become: true
  ansible.builtin.group:
    name: "{{ docker_group_default }}"
    state: present
    system: true
  when:
    - docker_cis_rule_1_1_2 | bool
  tags:
    - docker
    - rule_1_1_2

- name: "AUTOMATED | 1.1.2 | PATCH | Ensure only trusted users are allowed to control Docker daemon | create docker user"
  become: true
  ansible.builtin.user:
    name: "{{ docker_user_default }}"
    group: "{{ docker_group_default }}"
    groups: "{{ docker_group_default }}"
    comment: "manage docker access"
    system: true
    shell: "{{ docker_user_shell }}"
  when:
    - docker_cis_rule_1_1_2 | bool
  tags:
    - docker
    - rule_1.1.2

- name: "AUTOMATED | 1.1.2 | PATCH | Ensure only trusted users are allowed to control Docker daemon | adding users to group {{ docker_group_default }}"
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ docker_group_default }}"
    append: true
  loop: "{{ docker_users_to_add_group | flatten(levels=1) }}"
  when:
    - docker_cis_rule_1_1_2 | bool
    - docker_users_to_add_group is not none
    - docker_users_to_add_group | length>0
  tags:
    - docker
    - rule_1_1_2

# ------------------------------------------------------------------------------
- name: "AUTOMATED | 1.1.3 - 1.1.18 | PATCH | Check if auditd is installed"
  ansible.builtin.stat: path=/etc/init.d/auditd
  register: service_auditd_status
  tags:
    - docker
    - rule_1_1_3-18

- name: "AUTOMATED | 1.1.3 | PATCH | Ensure auditing is configured for the Docker daemon - /usr/bin/dockerd"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/dockerd(\\s|$)"
    line: "-w /usr/bin/dockerd -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_3 | bool
  tags:
    - docker
    - rule_1_1_3

- name: "AUTOMATED | 1.1.4 | PATCH | Ensure auditing is configured for Docker files and directories - /run/containerd"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-a exit,always -F path=/run/containerd(\\s|$)"
    line: "-a exit,always -F path=/run/containerd -F perm=war -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_4 | bool
  tags:
    - docker
    - rule_1_1_4

- name: "AUTOMATED | 1.1.5 | PATCH | Ensure auditing is configured for Docker files and directories - /var/lib/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-a exit,always -F path=/var/lib/docker(\\s|$)"
    line: "-a exit,always -F path=/var/lib/docker -F perm=war -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_5 | bool
  tags:
    - docker
    - rule_1_1_5

- name: "AUTOMATED | 1.1.6 | PATCH | Ensure auditing is configured for Docker files and directories - /etc/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /etc/docker(\\s|$)"
    line: "-w /etc/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_6 | bool
  tags:
    - docker
    - rule_1_1_6

- name: "AUTOMATED | 1.1.7 | PATCH | Ensure auditing is configured for Docker files and directories - docker.service"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/lib/systemd/system/docker.service(\\s|$)"
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_7 | bool
  tags:
    - docker
    - rule_1_1_7

- name: "AUTOMATED | 1.1.8 | PATCH | Ensure auditing is configured for Docker files and directories - containerd.sock"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /run/containerd/containerd.sock(\\s|$)"
    line: "-w /run/containerd/containerd.sock -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_8 | bool
  tags:
    - docker
    - rule_1_1_8

- name: "AUTOMATED | 1.1.9 | PATCH | Ensure auditing is configured for Docker files and directories - docker.socket"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /var/run/docker.sock(\\s|$)"
    line: "-w /var/run/docker.sock -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_9 | bool
  tags:
    - docker
    - rule_1_1_9

- name: "AUTOMATED | 1.1.10 | PATCH | Ensure auditing is configured for Docker files and directories - /etc/default/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /etc/default/docker(\\s|$)"
    line: "-w /etc/default/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_10 | bool
  tags:
    - docker
    - rule_1_1_10

- name: "AUTOMATED | 1.1.11 | PATCH | Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /etc/docker/daemon.json(\\s|$)"
    line: "-w /etc/docker/daemon.json -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_11 | bool
  tags:
    - docker
    - rule_1_1_11

- name: "AUTOMATED | 1.1.12 | PATCH | Ensure auditing is configured for Docker files and directories - /etc/containerd/config.toml"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /etc/containerd/config.toml(\\s|$)"
    line: "-w /etc/containerd/config.toml -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_12 | bool
  tags:
    - docker
    - rule_1_1_12

- name: "AUTOMATED | 1.1.13 | PATCH | Ensure auditing is configured for Docker files and directories - /etc/sysconfig/docker"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /etc/sysconfig/docker(\\s|$)"
    line: "-w /etc/sysconfig/docker -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_13 | bool
  tags:
    - docker
    - rule_1_1_13

- name: "AUTOMATED | 1.1.14 | PATCH | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/containerd(\\s|$)"
    line: "-w /usr/bin/containerd -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_14 | bool
  tags:
    - docker
    - rule_1_1_14

- name: "AUTOMATED | 1.1.15 | PATCH | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/containerd-shim(\\s|$)"
    line: "-w /usr/bin/containerd-shim -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_15 | bool
  tags:
    - docker
    - rule_1_1_15

- name: "AUTOMATED | 1.1.16 | PATCH | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v1"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/containerd-shim-runc-v1(\\s|$)"
    line: "-w /usr/bin/containerd-shim-runc-v1 -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_16 | bool
  tags:
    - docker
    - rule_1_1_16

- name: "AUTOMATED | 1.1.17 | PATCH | Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v2"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/containerd-shim-runc-v2(\\s|$)"
    line: "-w /usr/bin/containerd-shim-runc-v2 -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_17 | bool
  tags:
    - docker
    - rule_1_1_17

- name: "AUTOMATED | 1.1.18 | PATCH | Ensure auditing is configured for Docker files and directories - /usr/bin/runc"
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/docker_cis_rule_1_1_3-18.rules
    regexp: "^(#)?-w /usr/bin/runc(\\s|$)"
    line: "-w /usr/bin/runc -k docker"
    state: present
    mode: "640"
    create: true
  when:
    - service_auditd_status is defined
    - service_auditd_status.stat is defined
    - service_auditd_status.stat.exists is defined
    - service_auditd_status.stat.exists | bool
    - docker_cis_rule_1_1_18 | bool
  notify:
    - restart auditd-service
  tags:
    - docker
    - rule_1_1_18

# ------------------------------------------------------------------------------
- name: "MANUAL | 1.2.1 | INFO | Ensure the container host has been Hardened"
  ansible.builtin.debug:
    msg:
      - "###############################################"
      - "- Ensure the container host has been Hardened -"
      - "###############################################"
  when:
    - docker_cis_rule_1_2_1
  tags:
    - docker
    - rule_1_2_1

- name: "MANUAL | 1.2.2 | INFO | Ensure that the version of Docker is up to date"
  ansible.builtin.debug:
    msg:
      - "###################################################"
      - "- Ensure that the version of Docker is up to date -"
      - "###################################################"
  when:
    - docker_cis_rule_1_2_2
  tags:
    - docker
    - rule_1_2_2
