---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Run role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    cis_docker_user_shell: /bin/bash
    cis_docker_users_to_add_group:
      - name: "ubuntu"
    # cis_docker_storage_driver: overlay2
    # rootless not possible to test under docker, because reboot is current needed
    cis_docker_rule_2_1: false # rootless installation mode
    cis_docker_rule_2_10: false # namespace user isolation
    cis_docker_is_swarm_mode: true # enabled into swarm mode
    cis_docker_distribution_key_use_modern_sources: false # add apt source in modern style
