---
# handlers file for ansible-docker

# ------------------------------------------------------------------------------

- name: "HANDLER | 2.2.* | restart docker-service (ROOTLESS)"
  become: true
  become_user: "{{ cis_docker_user_default }}"
  ansible.builtin.service:
    name: docker.service
    state: restarted
    enabled: true
    # scope: user
  listen: Restart docker-service
  when:
    - cis_docker_rule_2_1

- name: "HANDLER | 2.2.* | restart docker-service"
  become: true
  ansible.builtin.service:
    name: docker.service
    state: restarted
    enabled: true
  listen: Restart docker-service
  when:
    - not cis_docker_rule_2_1

# ------------------------------------------------------------------------------

- name: "HANDLER | 1.1.18 | restart auditd-service"
  become: true
  ansible.builtin.systemd_service:
    name: auditd
    daemon_reload: true
    enabled: true
    masked: false
    state: restarted
  listen: Restart auditd-service
  when: ansible_virtualization_type != "docker"
