---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint . -c .yamllint
  ansible-lint -c .ansible-lint
platforms:
  - name: ubuntu-23.04
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:23.04
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      stdout_callback: yaml
      timeout: 10
      display_skipped_hosts: true
      show_per_host_start: true
      callbacks_enabled: community.general.yaml
      bin_ansible_callbacks: true
    ssh_connection:
      scp_if_ssh: true
      transfer_method: piped
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
