---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include ansible-docker"
      ansible.builtin.include_role:
        name: "ansible-docker"
  vars:
    # rootless not possible to test under docker, because reboot is current needed
    cis_docker_rule_2_1: false # to run install in rootless mode
    cis_docker_users_to_add_group:
      - name: "ubuntu"
    cis_docker_is_swarm_mode: true
